version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - copyloopvar
    - dupl
    - dupword
    - errname
    - errorlint
    - fatcontext
    - forcetypeassert
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - intrange
    - misspell
    - modernize
    - nakedret
    - nilerr
    - nilnil
    - perfsprint
    - prealloc
    - predeclared
    - recvcheck
    - thelper
    - unconvert
    - unparam
    - usestdlibvars
    - wastedassign
    - whitespace
    - rimbalint
  settings:
    custom:
      rimbalint:
        type: "module"
        description: "Rimba custom lint rules (nolocalstruct, nolateconst)"
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 3
      min-occurrences: 3
    dupl:
      threshold: 150
    errcheck:
      exclude-functions:
        - fmt.Fprint
        - fmt.Fprintf
        - fmt.Fprintln
        - os.RemoveAll
        - (io.ReadCloser).Close
    revive:
      rules:
        - name: unused-parameter
          disabled: true
        - name: exported
          disabled: true
        - name: package-comments
          disabled: true
  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      - path: (_test\.go|testutil/)
        linters: [gosec]
      - path: internal/agentfile/content\.go
        linters: [dupl]
