version: 2
project_name: rimba

builds:
  - main: .
    binary: rimba
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/lugassawan/rimba/cmd.version={{.Version}}
      - -X github.com/lugassawan/rimba/cmd.commit={{.ShortCommit}}
      - -X github.com/lugassawan/rimba/cmd.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt

release:
  name_template: "Release v{{ .Version }}"

changelog:
  sort: asc
  abbrev: -1
  groups:
    - title: "Features"
      regexp: '^.*\[feat\].*$'
      order: 0
    - title: "Bug Fixes"
      regexp: '^.*\[fix\].*$'
      order: 1
    - title: "Refactoring"
      regexp: '^.*\[refactor\].*$'
      order: 2
    - title: "Maintenance"
      regexp: '^.*\[chore\].*$'
      order: 3
    - title: "Other"
      order: 999
  filters:
    exclude:
      - '^\[docs\]'
      - '^\[test\]'
      - '^\[ci\]'
      - '^Initial commit$'
